x-postgres-env: &postgres-env
  POSTGRES_PASSWORD: proteinbind
  POSTGRES_USER: proteinbind
  POSTGRES_DB: proteinbind


services:

  postgres:
    image: postgres:16
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      <<: [*postgres-env]
    volumes:
      - ./data:/var/lib/postgresql/data/
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-sample-app
    environment:
      <<: [*postgres-env]
      DEBUG: 'true'
      COMPRESS_OFFLINE: 'false'
      PYTHONDONTWRITEBYTECODE: 1 
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /app/
