# Generated by Django 4.2.13 on 2024-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='atom_count',
            field=models.IntegerField(verbose_name='atom_count'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='number_of_chains',
            field=models.IntegerField(verbose_name='number_of_chains'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='sequence_length',
            field=models.IntegerField(verbose_name='sequence_length'),
        ),
    ]
