# Generated by Django 4.2.13 on 2024-07-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0002_alter_protein_atom_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protein',
            old_name='proten_name',
            new_name='protein_name',
        ),
    ]
