# Generated by Django 4.2.13 on 2024-07-12 13:28

from django.db import migrations

def generate_data(apps, schema_editor):

    Protein = apps.get_model("proteinapp", "Protein")

    Protein.objects.create(
        protein_name = "Urokinase-type plasminogen activator",
        uniprot_id = "P00749",
        experimental_method = "X-Ray",
        pdb_resolution = 1.61,
        number_of_chains = 1,
        sequence_length = 245,
        molecular_weight = 28.24,
        atom_count = 2143
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0003_rename_proten_name_protein_protein_name'),
    ]

    operations = [
        migrations.RunPython(generate_data),
    ]
