# Generated by Django 5.0.7 on 2024-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinapp', '0004_auto_20240712_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='atom_count',
            field=models.IntegerField(verbose_name='Atom Count'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='deposit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Deposit Date'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='experimental_method',
            field=models.CharField(max_length=255, verbose_name='Experimental Method'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='molecular_weight',
            field=models.FloatField(verbose_name='Molecular Weight'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='number_of_chains',
            field=models.IntegerField(verbose_name='Number Of Chains'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='pdb_resolution',
            field=models.FloatField(verbose_name='PDB Resolution'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_name',
            field=models.CharField(max_length=255, verbose_name='Protein Name'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='revision_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Revision Date'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='sequence_length',
            field=models.IntegerField(verbose_name='Sequence Length'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot_id',
            field=models.CharField(max_length=20, verbose_name='Uniprot ID'),
        ),
    ]
